%% Main functions

%% Settings
clearvars; clc
projectDir = 'D:\EmoStroop\\';

%% Extracte interested values
%% Non-time series data
Data = getValues(projectDir, ...
    'RT', ...
    [], ...
    {'group'}, ...
    {});
head(Data, 15)

Data = rmInsff(Data, 30);
head(Data, 15)

%% Time series data
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [], ...
    {'group'}, ...
    {});
head(Data, 15)

Data = getValues(projectDir, ...
    'Pupil_l', ...
    [1000 2000], ...
    {'group'}, ...
    {});

head(Data, 15)

%% Extract value according to multiple conditions
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [1000 2000], ...
    {'group','cond'}, ...
    {});

head(Data, 15)

%%
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [1000 2000], ...
    {'group','cond'}, ...
    {1, 2; ...
     2, 2});

Data = rmInsff(Data, 0);

head(Data, 15)

%% Plot data
%% Plot dynamic data
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [], ...
    {'group'}, ...
    {});

plotDynamic(Data, ...
    'tw', [-200 3999 -1000], ...
    'xlab', 'Time from target onset (ms)', ...
    'ylab', 'Pupil size (mm)', ...
    'col', [[0 .5 .8];[.8 .1 0]])

%
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [], ...
    {'group','cond'}, ...
    {});

plotDynamic(Data, ...
    'tw', [-200 3999 -1000], ...
    'xlab', 'Time from target onset (ms)', ...
    'ylab', 'Pupil size (mm)', ...
    'col', [[0 .5 .8];[.8 .1 0];[0 .5 .8];[.8 .1 0]], ...
    'lnstyle', {'-','-','--','--'})

%% Box plot
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [1000 2000], ...
    {'group','cond'}, ...
    {});

plotBox(Data, ...
    'dot', true, ...
    'col', [[0 .5 .8];[.8 .1 0];[0 .5 .8];[.8 .1 0]], ...
    'ylab', 'Pupil size (mm)');

%% Plot main sequence

op = plotSQ(projectDir, ...
    [0 2000], ...
    {'group','cond'}, ...
    {}, ...
    [[0 .5 .8];[.8 .1 0];[0 .5 .8];[.8 .1 0]]);

%% Plot polar rate distribution

op = plotPolar(projectDir, ...
    [0 2000], ...
    {'group','cond'}, ...
    {}, ...
    20, ...
    [[0 .5 .8];[.8 .1 0];[0 .5 .8];[.8 .1 0]], ...
    {'-','-','--','--'}, ...
    true);


%% Analysis
%% t-test
Data = getValues(projectDir, ...
    'RT', ...
    [], ...
    {'group'}, ...
    {});

doTTest(Data, ...
    'RT', ...
    'group', ...
    {1 2}, ...
    false, ...
    'both');

%% Two-way mixed ANOVA
Data = getValues(projectDir, ...
    'RT', ...
    [], ...
    {'group','cond'}, ...
    {});

mixed_anova(Data, ...
    'RT', ...
    'group', ...
    'cond', ...
    false);

%% Principle component analysis (PCA)
Data = getValues(projectDir, ...
    'Pupil_l', ...
    [], ...
    {'group','cond'}, ...
    {});

doPCA(Data,'Pupil_l',[1 4000 -1000])

