function montageCode=ep_montage
% ep_montage - montageCode=ep_montage(montageName) -
% Provides montage list and codes.
%
%Input:
%
%Output:
%  montageCode : The code for the montage.

%History
%  by Joseph Dien (8/6/21)
%  jdien07@mac.com
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     Copyright (C) 1999-2025  Joseph Dien
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    montageCode = {'Adult GSN200 128-channel 2.1';...
        'Adult GSN 128-channel 1.0';...
        'Adult Recumbent GSN 128-channel 1.0';...
        'Adult GSN 64-channel 1.0';...
        'Infant GSN 64-channel 1.0';...
        'Toddler GSN 64-channel 1.0';...
        'Adult GSN 64-channel 2.0';...
        'Adult preGSN 64-channel 1.0';...
        'Adult GSN 256-channel 2.0';...
        'Adult GSN 256-channel 2.1';...
        'Adult Hydrocel 32-channel 1.0';...
        'Adult Hydrocel 64-channel 1.0';...
        'Adult Hydrocel 128-channel 1.0';...
        'Adult Hydrocel 256-channel 1.0';...
        'Generic 10-05'};
